### PR TITLE
Category feature

### PR DESCRIPTION
**Pull request by SuyashFowdar**
In this feature, the following have been done.

- Create rails app
- Create models, controllers and views for user
- Create models, controllers and views for article
- Create models, controllers and views for category
- Create models and controllers for vote
- Create models and controllers for article_category
- Allow creation of new user
- Allow user to sign in using name
- Allow user to create new article
- Allow user to view homepage with 1 most recent article for each category and 1 most voted article
- Allow user to view articles ordered from the latest, for each category
- Allow user to search for a specific article by title
- Add style to adapt design given in requirement

Thank you.

### CODE REVIEW

**Comment by SuyashFowdar** [comment]
The changes for first review set are in the following commits.

https://github.com/krishnzzz/tech-news/commit/47414db45ee643b78a448c323974e0b576502a93

https://github.com/krishnzzz/tech-news/commit/7548b0b5e233cd2319605a6a10427023c28d6b75

Please note that, upon discussing with the second TSE, the following points were agreed upon to be in "Nice to have" section instead of mandatory "To Improve" section, since they were not in project requirement.

- When you create a new article instead of being redirected to the home page you could go to the article show page.
- I can vote but can't see how many votes an article has.
- Please, make clickable the article's title on HomePage. We should be able to read the article by clicking directly on the article's title
- It's no even possible to read an article. How to do it, please? How to read the article, please?

Thank you.

**Comment by SuyashFowdar** [comment]
Please run `db:create`, `db:migrate` and `db:seed` instead of `db:setup` to have the app running. There seems to be an issue with `db:setup` in having the app running properly.

Thank you.

**Comment by rindrajosia** [comment]
> Please run `db:create`, `db:migrate` and `db:seed` instead of `db:setup` to have the app running. There seems to be an issue with `db:setup` in having the app running properly.
> 
> Thank you.

`db:create`, `db:migrate` and `db:seed` don't work, it should be 'rails db:create',  'rails db:migrate' and  'rails db:seed'

**Comment by SuyashFowdar** [comment]
> > Please run `db:create`, `db:migrate` and `db:seed` instead of `db:setup` to have the app running. There seems to be an issue with `db:setup` in having the app running properly.
> > Thank you.
> 
> `db:create`, `db:migrate` and `db:seed` don't work, it should be 'rails db:create', 'rails db:migrate' and 'rails db:seed'

Yes of course. Thank you.

**Pull request merged**
